// Generated by scripts/tiled-rooms.mjs. Do not edit.
export const roomLayouts = {
  "floor_0_lobby": {
    "width": 960,
    "height": 640,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 960,
      "bottom": 640
    },
    "obstacles": [
      {
        "x": 64,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 64,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 160,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 97,
        "width": 32,
        "height": 31
      },
      {
        "x": 448,
        "y": 97,
        "width": 32,
        "height": 31
      },
      {
        "x": 480,
        "y": 97,
        "width": 32,
        "height": 31
      },
      {
        "x": 512,
        "y": 97,
        "width": 32,
        "height": 31
      },
      {
        "x": 416,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 128,
        "width": 32,
        "height": 32
      },
      {
        "x": 327,
        "y": 172,
        "width": 18,
        "height": 20
      },
      {
        "x": 416,
        "y": 160,
        "width": 32,
        "height": 31
      },
      {
        "x": 448,
        "y": 160,
        "width": 32,
        "height": 31
      },
      {
        "x": 480,
        "y": 160,
        "width": 32,
        "height": 31
      },
      {
        "x": 512,
        "y": 160,
        "width": 32,
        "height": 31
      },
      {
        "x": 615,
        "y": 172,
        "width": 18,
        "height": 20
      },
      {
        "x": 160,
        "y": 224,
        "width": 32,
        "height": 32
      },
      {
        "x": 440,
        "y": 241,
        "width": 8,
        "height": 12
      },
      {
        "x": 448,
        "y": 241,
        "width": 32,
        "height": 15
      },
      {
        "x": 480,
        "y": 241,
        "width": 32,
        "height": 15
      },
      {
        "x": 512,
        "y": 241,
        "width": 8,
        "height": 12
      },
      {
        "x": 768,
        "y": 224,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 352,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 352,
        "width": 32,
        "height": 32
      }
    ],
    "spawns": [
      {
        "x": 480,
        "y": 544
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  }
} as const;
