// Generated by scripts/tiled-rooms.mjs. Do not edit.
export const roomLayouts = {
  "floor_0_lobby": {
    "width": 960,
    "height": 640,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 960,
      "bottom": 640
    },
    "obstacles": [],
    "spawns": [
      {
        "x": 480,
        "y": 544
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  }
} as const;
