// Generated by scripts/tiled-rooms.mjs. Do not edit.
export const roomLayouts = {
  "floor_0_lobby": {
    "width": 960,
    "height": 640,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 960,
      "bottom": 640
    },
    "obstacles": [
      {
        "x": 53,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 64,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 896,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 288,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 288,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 320,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 320,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 352,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 352,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 384,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 384,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 416,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 416,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 448,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 448,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 480,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 480,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 512,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 512,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 544,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 544,
        "width": 11,
        "height": 32
      },
      {
        "x": 64,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 96,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 128,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 160,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 192,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 224,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 256,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 288,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 320,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 352,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 384,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 416,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 448,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 480,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 512,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 544,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 576,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 608,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 640,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 672,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 704,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 736,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 768,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 800,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 832,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 864,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 896,
        "y": 576,
        "width": 11,
        "height": 11
      },
      {
        "x": 240,
        "y": 170,
        "width": 16,
        "height": 22
      },
      {
        "x": 256,
        "y": 170,
        "width": 32,
        "height": 22
      },
      {
        "x": 288,
        "y": 170,
        "width": 16,
        "height": 22
      },
      {
        "x": 240,
        "y": 192,
        "width": 16,
        "height": 32
      },
      {
        "x": 288,
        "y": 192,
        "width": 16,
        "height": 32
      },
      {
        "x": 236,
        "y": 224,
        "width": 20,
        "height": 16
      },
      {
        "x": 256,
        "y": 224,
        "width": 32,
        "height": 16
      },
      {
        "x": 288,
        "y": 224,
        "width": 20,
        "height": 16
      },
      {
        "x": 288,
        "y": 224,
        "width": 20,
        "height": 16
      },
      {
        "x": 160,
        "y": 224,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 224,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 224,
        "width": 32,
        "height": 16
      },
      {
        "x": 832,
        "y": 224,
        "width": 32,
        "height": 16
      },
      {
        "x": 384,
        "y": 352,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 352,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 519,
        "width": 32,
        "height": 25
      },
      {
        "x": 864,
        "y": 519,
        "width": 32,
        "height": 25
      },
      {
        "x": 66,
        "y": 544,
        "width": 28,
        "height": 32
      },
      {
        "x": 98,
        "y": 554,
        "width": 28,
        "height": 22
      },
      {
        "x": 834,
        "y": 554,
        "width": 28,
        "height": 22
      },
      {
        "x": 866,
        "y": 544,
        "width": 28,
        "height": 32
      }
    ],
    "spawns": [
      {
        "name": "default_door_spawn",
        "x": 624,
        "y": 240
      },
      {
        "name": "default_elevator_spawn",
        "x": 736,
        "y": 256
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  },
  "templates/appartment_template/default": {
    "width": 480,
    "height": 320,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 480,
      "bottom": 320
    },
    "obstacles": [
      {
        "x": 32,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 32,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 64,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 96,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 128,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 160,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 192,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 224,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 256,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 288,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 320,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 352,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 384,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 416,
        "y": 288,
        "width": 32,
        "height": 9
      },
      {
        "x": 160,
        "y": 85,
        "width": 32,
        "height": 11
      },
      {
        "x": 160,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 128,
        "width": 32,
        "height": 26
      }
    ],
    "spawns": [
      {
        "name": "default_appartment_door_spawn",
        "x": 240,
        "y": 144
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  },
  "templates/lobby_template/default": {
    "width": 960,
    "height": 640,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 960,
      "bottom": 640
    },
    "obstacles": [
      {
        "x": 53,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 64,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 480,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 512,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 544,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 576,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 608,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 640,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 672,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 704,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 736,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 768,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 800,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 832,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 864,
        "y": 192,
        "width": 32,
        "height": 32
      },
      {
        "x": 896,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 288,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 288,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 320,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 320,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 352,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 352,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 384,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 384,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 416,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 416,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 448,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 448,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 480,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 480,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 512,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 512,
        "width": 11,
        "height": 32
      },
      {
        "x": 53,
        "y": 544,
        "width": 11,
        "height": 32
      },
      {
        "x": 896,
        "y": 544,
        "width": 11,
        "height": 32
      },
      {
        "x": 64,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 96,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 128,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 160,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 192,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 224,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 256,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 288,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 320,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 352,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 384,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 416,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 448,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 480,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 512,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 544,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 576,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 608,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 640,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 672,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 704,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 736,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 768,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 800,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 832,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 864,
        "y": 576,
        "width": 32,
        "height": 11
      },
      {
        "x": 896,
        "y": 576,
        "width": 11,
        "height": 11
      }
    ],
    "spawns": [
      {
        "name": "default_door_spawn",
        "x": 480,
        "y": 544
      },
      {
        "name": "default_elevator_spawn",
        "x": 480,
        "y": 256
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  },
  "templates/small_room_template/default": {
    "width": 480,
    "height": 320,
    "bounds": {
      "left": 0,
      "top": 0,
      "right": 480,
      "bottom": 320
    },
    "obstacles": [
      {
        "x": 21,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 32,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 64,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 32,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 64,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 96,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 128,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 160,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 192,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 224,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 256,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 288,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 320,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 352,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 384,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 416,
        "y": 96,
        "width": 32,
        "height": 32
      },
      {
        "x": 448,
        "y": 96,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 128,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 160,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 192,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 224,
        "width": 11,
        "height": 32
      },
      {
        "x": 21,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 448,
        "y": 256,
        "width": 11,
        "height": 32
      },
      {
        "x": 32,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 64,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 96,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 128,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 160,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 192,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 224,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 256,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 288,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 320,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 352,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 384,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 416,
        "y": 288,
        "width": 32,
        "height": 11
      },
      {
        "x": 448,
        "y": 288,
        "width": 11,
        "height": 11
      }
    ],
    "spawns": [
      {
        "name": "default_room_spawn",
        "x": 240,
        "y": 240
      }
    ],
    "playerFootprint": {
      "width": 20,
      "height": 10
    }
  }
} as const;
